app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from . import login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(120), unique=True)
    password_hash = db.Column(db.String(128))
    parcels = db.relationship('Parcel', backref='sender', lazy='dynamic')
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        return AttributeError('You cannot read the password attribute')
    


    def verify_password(self, password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def save_user(self):
        db.session.add(self)
        db.session.commit()


class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    is_admin = db.Column(db.Boolean, default=False)
    users = db.relationship('User', backref='role', lazy="dynamic")

    def __repr__(self):

        return '<Role {}>'.format(self.is_admin)

class Parcel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    details = db.Column(db.String(140))
    status = db.Column(db.String(20))
    location = db.Column(db.String(20))
    recipient = db.Column(db.String(20))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def save_parcel(self):
        db.session.add(self)
        db.session.commit()

    def cancel_parcel(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def get_parcel(cls,id):
        parcels=Parcel.query.filter_by(user_id=id).all()
        return parcels

 
    def __repr__(self):
        return '<Parcel {}>'.format(self.details)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
import email_validator
from wtforms.validators import Required 

class ParcelForm(FlaskForm):
    details =TextAreaField('Enter parcel details', validators=[Required()])
    status = StringField('Status', validators=[Required()])
    location = StringField('Location', validators=[Required()])
    recipient = StringField('Recipient', validators=[Required()])
    submit = SubmitField('Add Parcel')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'



def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])


    db.init_app(app)
    login_manager.init_app(app)
  
   
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app


  

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template, url_for, request, flash, redirect
from . import main
from .forms import ParcelForm
from ..models import Parcel, User
from flask_login import login_required, current_user
from .. import db


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/parcel', methods=['GET', 'POST'])
@login_required
def parcel():
    form = ParcelForm()
    if form.validate_on_submit():
        details = form.details.data
        status = form.status.data
        location = form.location.data
        recipient = form.recipient.data
        parcel = Parcel(details= details, status= status, location= location, sender= current_user)
        
        db.session.add(parcel)
        db.session.commit()


    return render_template('parcel.html', form=form)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    user_id = current_user.id
    parcels = Parcel.query.filter_by(user_id=user_id).all()

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user=user, parcels=parcels)

@main.route('/parcels/<int:parcel_id>/delete', methods = ['POST', 'GET'])
@login_required
def delete(parcel_id):
    parcel = Parcel.query.get(parcel_id)
    if parcel.sender != current_user:
        abort(403)
    
    
    db.session.delete(parcel)
    db.session.commit()
    
    return redirect(url_for('.index',parcel=parcel))

@main.route('/parcel/<parcel_id>/update', methods = ['GET','POST'])
@login_required
def update_parcel(parcel_id):
    parcel = Parcel.query.get(parcel_id)
    if parcel.sender != current_user:
        abort(403)
        
    form = ParcelForm()
    if form.validate_on_submit():
        parcel.details = form.details.data
        parcel.status = form.status.data
        parcel.location = form.location.data
        parcel.recipient = form.recipient.data
       
        db.session.commit()
        
        flash('You have updated your Parcel!', 'success')
        
        return redirect(url_for('main.index',id = parcel.id)) 
    
    if request.method == 'GET':
        form.details.data = parcel.details 
        form.status.data = parcel.status 
        form.location.data = parcel.location 
        form.recipient.data = parcel.recipient 
        
        
    return render_template('parcel.html', form = form, legend='Update Parcel')

@main.route('/admin')
@login_required
def admin():
    parcels = Parcel.query.all()

    return render_template('admin.html', parcels=parcels)

app/templates/admin.html
{% extends 'base.html'%}
{% block content %}

<ul>
    {% for parcel in parcels %}
    <li>{{ parcel.details }}</li>
    <li>{{ parcel.status }}</li>
    <li>{{ parcel.location }}</li>
    <li>{{ parcel.timestamp }}</li>
    <li>{{ parcel.recipient }}</li>
    <li>{{ parcel.sender.username }}</li>
    <li><a href="{{url_for('main.update_parcel', parcel_id=parcel.id)}}" class="btn btn-success">Update</a></li>
    <li><a href="{{url_for('main.delete', parcel_id=parcel.id)}}" class="btn btn-danger">Cancel</a></li>

    {% endfor %}

</ul>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>SendIT</title>
    {% endif %}
  </head>

  <body>
    {% block navbar%}
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">SENDIT</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarScroll"
          aria-controls="navbarScroll"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul
            class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll"
            style="--bs-scroll-height: 100px"
          >
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.parcel')}}">Parcels</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.profile', uname=current_user.username)}}">Profile</a>
            </li>
            {% if current_user.is_admin ==True %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.admin')}}">Admin</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
            </li>
      
          </ul>
        </div>
      </div>
    </nav>
    {% endblock%} {% block content%} {% endblock %}
    <footer class="footer text-center">
      <span>&copy; 2021. Built by <a href="#">OLYMPIANS GROUP ONE</a></span>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
      integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
      integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/errors.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<img src="https://webdeasy.de/wp-content/uploads/2020/06/404-pages-850x365.jpg" alt="404" style="margin-left: 18%;">
<h1 class="text-center">Sorry. Couldn't find that page</h1>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="fill-height">
  <div class="row">
    <div class="col-lg-1"></div>
    <div id="hello" class="col-lg-10" style="text-align: center">
      <h1>SEND<span style="color: #f97300">IT</span></h1>
      <p>Delivering Packages Since 2021</p>
      <a href="{{url_for('auth.register')}}" class="btn btn-secondary btn-large">Sign Up</a>
      <a href="{{url_for('auth.login')}}" class="btn btn-secondary btn-large">Sign In</a>

    </div>
    <div class="col-lg-1"></div>
  </div>
</div>

{% endblock %}

app/templates/parcel.html
{% extends 'base.html'%}
{% block content%}
<h1>Hi, {{ current_user.username }}</h1>

<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add Parcel</legend>
      <div class="form-group">
        {{ form.details.label(class="form-control-label") }} 
        {{ form.details(class="form-control form-control-lg") }} 
        {% for error in form.details.errors %}
        <span class="danger text-muted">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.status.label(class="form-control-label") }} 
        {{ form.status(class="form-control form-control-lg") }} 
        {% for error in form.status.errors %}
        <span class="danger text-muted">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.location.label(class="form-control-label") }} 
        {{ form.location(class="form-control form-control-lg") }} 
        {% for error in form.location.errors %}
        <span class="danger text-muted">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.recipient.label(class="form-control-label") }}
        {{ form.recipient(class="form-control form-control-lg") }}
        {% for error in form.recipient.errors %}
        <span class="danger text-muted">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.submit (class = "btn btn-outline-info") }}
      </div>
    </fieldset>
  </form>


{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}

<table>
    <thead>
        <tr>
            <th>Details</th>
            <th>Sender</th>
            <th>Reciever</th>
            <th>Location</th>
            <th>Status</th>
            <th>Sent On</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {%for parcel in parcels%}
            <td>{{ parcel.sender.username }}</td>
            <td>{{ parcel.recipient }}</td>
            <td>{{ parcel.details }}</td>
            <td>{{ parcel.location }}</td>
            <td>{{ parcel.status }}</td>
            <td>{{ parcel.timestamp }}</td>
            <td>
                <a href="{{url_for('main.update_parcel', parcel_id=parcel.id)}}" class="btn btn-success">Update</a>
                <a href="{{url_for('main.delete', parcel_id=parcel.id)}}" class="btn btn-danger">Cancel</a>
            </td>
        </tr>
    </tbody>
    {% endfor %}


{% endblock %}